---


- name: Edit php-fpm.conf file
  template:
    src: php-fpm.j2
    dest: /etc/php/7.2/fpm/pool.d/www.conf 
    mode: 0775

- name: Edit php.ini file
  template:
    src: php.ini.j2
    dest: /etc/php/7.2/fpm/php.ini
    mode: 0775

- name: Ensure nginx is restarted
  service:
    name: "{{ webserver_daemon }}"
    state: "restarted"
    enabled: "true"

- name: Ensure phpfpm is restarted
  service:
    name: "php7.2-fpm"
    state: "restarted"
    enabled: "true"