---
- name: Install PHP dependencies
  apt: 
    name: "{{ item }}"
    update_cache: true
    state: latest
  with_items:
    - zip
    - unzip
  tags: packages

- name: Install PHP 7.2
  apt: 
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items:
    - php7.2
    - php7.2-cli
    - php7.2-fpm
    - php7.2-common
  tags: packages

- name: Install PHP 7.2 additionnal packages
  apt: 
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items:
    - {{ php_packages }}
  tags: packages

- name: Ensure the nginx service is running
  service: 
    name: "{{ webserver_daemon }}"
    state: started 
    enabled: yes

- name: Ensure the php7.2-fpm service is running
  service: 
    name: "php7.2-fpm"
    state: started 
    enabled: yes